// <copyright file="NameToken.cs" company="Visualisierungsinstitut der Universität Stuttgart">
// Copyright © 2024 Visualisierungsinstitut der Universität Stuttgart.
// Licensed under the MIT licence. See LICENCE file for details.
// </copyright>
// <author>Christoph Müller</author>

using System;
using System.Diagnostics;
using System.Text.Unicode;


namespace Visus.BibTex {

    /// <summary>
    /// Represents a token generated by the <see cref="NameTokeniser"/>.
    /// </summary>
    /// <param name="type">The type of the token.</param>
    /// <param name="text">The content of the token.</param>
    [DebuggerDisplay("{Type}: {Text}")]
    internal ref struct NameToken(NameTokenType type, ReadOnlySpan<char> text) {

        #region Public properties
        /// <summary>
        /// Answer whether the token starts with a capital letter.
        /// </summary>
        public bool IsCapitalised => (this.Text.Length > 0)
            && (char.IsUpper(this.Text[0])
            || UnicodeRanges.CjkUnifiedIdeographs.Contains(this.Text[0]));

        /// <summary>
        /// Gets the content of the token.
        /// </summary>
        public ReadOnlySpan<char> Text { get; } = text;

        /// <summary>
        /// Gets the type of the token.
        /// </summary>
        public NameTokenType Type { get; } = type;
        #endregion

        #region Public methods
        /// <inheritdoc />
        public override string ToString() => this.Text.ToString();
        #endregion
    }
}
